name = "r2-assets"
main = "src/index.ts"
compatibility_date = "2024-09-01"

# Replace with your Cloudflare account ID
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

[vars]
# Optional: prefix or configuration values can be set here.

[[r2_buckets]]
binding = "ASSETS"         # available in code as env.ASSETS
bucket_name = "YOUR_R2_BUCKET_NAME"

# To attach a custom domain later:
# [routes]
# pattern = "assets.yourdomain.com/*"

